### ISSUE TITLE
Pdf download of dashboard

### ISSUE THREAD

**Issue by matteoberla** [alnitak/flutter_flow_chart#21]
Is it possible to download the pdf version of the dashboard created? i think it would be useful to export and be able to print the canvas.

**Comment by SL-Pirate** [comment]
No, I don't know if that's feasible. I am aware that certain packages enable the conversion of widgets for exportation to PDF format; however, these products necessitate the importation of widgets directly from the package. It won't actually be feasible because of the intricacy and the need for unique paint objects, among other things. 

As a solution, though, I could recommend using a plugin that lets you take a photo or picture of a specific widget and use it to generate a PDF. Again, though, I haven't personally tested it, so this is just a possibility.

**Comment by matteoberla** [comment]
So will you add the possibility to get an image of the entire canvas and export it?

**Comment by SL-Pirate** [comment]
No I said you could try to do it
outside the package, in your code from your side.
I don't think it's a good idea to add such a feature to the package itself considering the package is gonna have to depend on another package. Not really worth it.

**Comment by matteoberla** [comment]
I've tried with the screenshot package in order to get an image and then convert it to pdf.
The problem is that it doesn't get the entire screen even if some components are hidden, if i try to scale down the elements are too small to be seen and then a screen aspect ratio could be different from an A4 pdf.

Any idea to get the whole content of the dashboard and fit the pdf content?
Thank you

**Comment by alnitak** [comment]
You can try to use [Capturing Widgets that are not in the widget tree](https://pub.dev/packages/screenshot#capturing-widgets-that-are-not-in-the-widget-tree) and give it a `Dashboard` larger than the device screen.

I close this issue since the `capture Dashboard` feature is not (yet) planned.

**Comment by matteoberla** [comment]
Already tried, when passing FlowChart Widget as parameter:

```
The following assertion was thrown building Draggable<FlowElement>(dirty, state: _DraggableState<FlowElement>#bd279):
No Overlay widget found.

Draggable<FlowElement> widgets require an Overlay widget ancestor within the closest LookupBoundary.
An overlay lets widgets float on top of other widget children.

To introduce an Overlay widget, you can either directly include one, or use a widget that contains an Overlay itself, such as a Navigator, WidgetApp, MaterialApp, or CupertinoApp.
```

tried then to wrap in a MaterialApp widget but leds to another error.
I'm not getting if i'm doing something wrong with your widget.
