### ISSUE TITLE
Change arrow style

### ISSUE THREAD

**Issue by MalcolmMielle** [alnitak/flutter_flow_chart#3]
It's a very nice package! Would it be possible to add an example on how to change the arrow style?

**Comment by alnitak** [comment]
Hi and thank you very much, it's now only possible to change the thickness of the arrows and the end point it's only a filled circle.
If you want to change the filled circle with something other (ie an arrow), the line code is this:
https://github.com/alnitak/flutter_flow_chart/blob/95279a6af14cb189788869b2286e8ee4affb486c/lib/src/ui/draw_arrow.dart#L243
I don't know yet when I will be able to look at this due to few spare time! So please feel free to do a PR!

**Comment by MalcolmMielle** [comment]
No worries, I'll send a PR if I end up doing it :)

**Comment by alr2413** [comment]
It would be nice, if we can also set a text for arrow.
